
---

## `.github/workflows/build-bankstatement-api.yml`

```yaml
name: Build & Push bankstatement-api

on:
  push:
    branches: [ main, master ]
    paths:
      - 'bankstatement-api/**'
      - '.github/workflows/build-bankstatement-api.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/bankstatement-api
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./bankstatement-api
          file: ./bankstatement-api/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
